# <h1 align = "center"> Proiect ⟶ Testele PISA 2022</h1>

Student ⟶ Victor-Nicolae MATVEEV, anul I, **MASTER**

---

Universitatea Națională de Știință și Tehnologie POLITEHNICĂ București \
Facultatea de Științe Aplicate ⟶ Teoria Codării și Stocării Informației

---

EXAMEN IUNIE 2026


---

# Introducere & Ipoteză de lucru & Descriere scurtă a setului de date

Testul <font color = "red">PISA</font> apărut în anul 1997, se mai spune și studiul internațional al studenților organizat de OCDE ↔ Organizația pentru Cooperare & Dezvoltare Economică, este orientat pe <font color = "red">evaluarea compentențelor de bază ale elevilor de ~15 ani</font>.

Ideea generală este că nu este vorba despre cât de bine au <font color = "red">memorat elevii</font> materiile școlare, ci capacitatea de a <font color = "red">aplica cunoștințele acumulate </font> care pot fi folosiți pentru rezolvarea problemelor ce pot apărea în viață → provocări neprevăzute în societate. De exemplu, putem lua în considerare testarea coeficientului de inteligență [IQ].

Pe de altă parte, ce e interesant este că fix în anul 2022 a apărut un domeniu nou & util bazat pe <font color = "red">gândirea creativă</font>.

<blockquote>
Acest set de date este configurat & extras din mai multe baze de date PISA din anul 2022.
</blockquote>

De regulă, testarea PISA se concentrează pe 3 domenii fundamentale:

*   `Math` → matematică → înțelegerea & rezolvarea problemelor practice
*   `Read` → lectură → înțelegerea & identificarea informațiilor necesare
*   `Science` → știință → înțelegerea & analizarea datelor

Pe lângă acest lucru, se mai adaug niște variabile referitoare la:


*   `MathGirl` & `ReadGirl` & `ScienceGirl` → categoria de fete
*   `MathBoy` & `ReadBoy` & `ReadBoy` → categoria de băieți

Un exemplu concret din setul de date referitor la țara România se poate observa mai jos.

In [ ]:
set_de_date[set_de_date['Country'] == 'Romania']

,Country,Math,Read,Science,MathGirl,MathBoy,ReadGirl,ReadBoy,ScienceGirl,ScienceBoy
64,Romania,428,428,428,425,430,442,415,428,427

Fiecare domeniu în funcție de rezultatele obținute al elevilor la fiecare țară este notat un scor PISA. De asemenea, domeniile sunt împărțite în două categorii.

# Cod Python utile pentru sarcini de lucru

In [ ]:
# importare drive din Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# citirea setului de date configurat [.csv]
import pandas as pd

set_de_date = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/proiectEXAMEN/PISA2022_set_de_date.csv')

In [ ]:
set_de_date

,Country,Math,Read,Science,MathGirl,MathBoy,ReadGirl,ReadBoy,ScienceGirl,ScienceBoy
0,OECD average,472,476,485,468,477,488,464,485,485
1,Albania,368,358,376,378,359,379,339,391,362
2,Argentina,378,401,406,372,383,408,394,403,409
3,Australia,487,498,507,481,493,509,487,506,508
4,Austria,487,480,491,478,497,491,470,485,497
...,...,...,...,...,...,...,...,...,...,...
77,United Kingdom,489,494,500,482,496,503,486,496,504
78,United States,465,504,499,458,471,515,493,496,503
79,Uruguay,409,430,435,403,414,438,423,431,440
80,Uzbekistan,364,336,355,361,367,347,325,357,353
81,Viet Nam,469,462,472,464,475,471,453,470,475

# Rezultatele obținute pe baza calculelor statistice

# Explicații & comentarii ale rezultatelor statistice

# Grafice relevante pentru ipoteză de lucru

# Explicații & comentarii ale graficelor

# Concluzii generale