# <h1 align = "center"> Proiect ⟶ Testele PISA 2022</h1>

Student ⟶ Victor-Nicolae MATVEEV, anul I, **MASTER**

---

Universitatea Națională de Știință și Tehnologie POLITEHNICĂ București \
Facultatea de Științe Aplicate ⟶ Teoria Codării și Stocării Informației

---

EXAMEN IUNIE 2026


---

# Introducere & Ipoteză de lucru & Descriere scurtă a setului de date

Testul <font color = "red">PISA</font> apărut în anul 1997, se mai spune și studiul internațional al studenților organizat de OCDE ↔ Organizația pentru Cooperare & Dezvoltare Economică, este orientat pe <font color = "red">evaluarea compentențelor de bază ale elevilor de ~15 ani</font>.

Ideea generală este că nu este vorba despre cât de bine au <font color = "red">memorat elevii</font> materiile școlare, ci capacitatea de a <font color = "red">aplica cunoștințele acumulate </font> care pot fi folosiți pentru rezolvarea problemelor ce pot apărea în viață → provocări neprevăzute în societate. De exemplu, putem lua în considerare testarea coeficientului de inteligență [IQ].

Scopul testelor PISA este ca fiecare țară să-și <font color = "red">imbunătățească mediul educațional</font> → decizii guvernamentale în privința investițiilor & perfomanțele sistemelor de educație prin evaluări periodice. Din punct de vedere, impactul evaluărilor internaționale este concludent. Adevărul este că când vine vorba mereu despre 'educație', influența politică a existat în mod direct & indirect și există întotdeauna.

Acest proiect construit are următoarele 3 ipoteze principale:


*   Media rezultatelor obținute din testele PISA pentru fiecare continent [Asia, Africa, America de Nord, America de Sud, Antarctica, Europa & Australia]. Pe baza rezultatelor statistice, care continent are elevi cu rezultatele mai bune în cadrul testelor PISA 2022?
*   Așa cum susține lumea, este adevărat că fetele au perfomanțe mai bune decât băieții?
*   Care este poziția României & țările vecine [Moldova, Bulgaria, Ucraina, Ungaria & Serbia] față de media OECD?

<blockquote>
Acest set de date este configurat & extras din mai multe baze de date PISA din anul 2022.
</blockquote>

Pe de altă parte, ce e interesant este că fix în anul 2022 a apărut un domeniu nou & util bazat pe <font color = "red">gândirea creativă</font>.

De regulă, testarea PISA se concentrează pe 3 domenii fundamentale:

*   `Math` → matematică → înțelegerea & rezolvarea problemelor practice
*   `Read` → lectură → înțelegerea & identificarea informațiilor necesare
*   `Science` → știință → înțelegerea & analizarea datelor

Pe lângă acest lucru, se mai adaug niște variabile referitoare la:


*   `MathGirl` & `ReadGirl` & `ScienceGirl` → categoria de fete pe 3 domenii
*   `MathBoy` & `ReadBoy` & `ReadBoy` → categoria de băieți pe 3 domenii

Un exemplu concret din setul de date referitor la țara România se poate observa mai jos.

In [ ]:
set_de_date[set_de_date['Country'] == 'Romania']

,Country,Math,Read,Science,MathGirl,MathBoy,ReadGirl,ReadBoy,ScienceGirl,ScienceBoy
64,Romania,428,428,428,425,430,442,415,428,427

Se observă că fiecare domeniu în funcție de rezultatele obținute al elevilor la fiecare țară este notat un scor PISA. De asemenea, domeniile sunt împărțite în două categorii → fete și băieți.

# Cod Python utile pentru sarcini de lucru

In [2]:
# importare drive din Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# citirea setului de date configurat [.csv]
import pandas as pd

set_de_date = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/proiectEXAMEN/PISA2022_set_de_date.csv')

In [22]:
# afișarea setului de date
set_de_date

,Country,Math,Read,Science,MathGirl,MathBoy,ReadGirl,ReadBoy,ScienceGirl,ScienceBoy
0,OECD average,472,476,485,468,477,488,464,485,485
1,Albania,368,358,376,378,359,379,339,391,362
2,Argentina,378,401,406,372,383,408,394,403,409
3,Australia,487,498,507,481,493,509,487,506,508
4,Austria,487,480,491,478,497,491,470,485,497
...,...,...,...,...,...,...,...,...,...,...
77,United Kingdom,489,494,500,482,496,503,486,496,504
78,United States,465,504,499,458,471,515,493,496,503
79,Uruguay,409,430,435,403,414,438,423,431,440
80,Uzbekistan,364,336,355,361,367,347,325,357,353
81,Viet Nam,469,462,472,464,475,471,453,470,475

# Rezultatele obținute pe baza calculelor statistice

In [38]:
# calcule statistice pentru Asia
medie_m_asia = set_de_date.loc[[8, 10, 13, 29, 32, 34, 37, 38, 39, 40, 44, 45, 49, 56, 60, 63, 65, 67, 73, 76, 80, 81]]['Math'].mean()
medie_r_asia = set_de_date.loc[[8, 10, 13, 29, 32, 34, 37, 38, 39, 40, 44, 45, 49, 56, 60, 63, 65, 67, 73, 76, 80, 81]]['Read'].mean()
medie_s_asia = set_de_date.loc[[8, 10, 13, 29, 32, 34, 37, 38, 39, 40, 44, 45, 49, 56, 60, 63, 65, 67, 73, 76, 80, 81]]['Science'].mean()

# calcule statistice pentru Africa [doar Morocco]
medie_m_africa = set_de_date.loc[[51]]['Math'].mean()
medie_r_africa = set_de_date.loc[[51]]['Read'].mean()
medie_s_africa = set_de_date.loc[[51]]['Science'].mean()
print(medie_m_africa)

# calcule statistice pentru America de Nord
medie_m_america_nord = set_de_date.loc[[11, 15, 20, 21, 28, 36, 47, 57, 78]]['Math'].mean()
medie_r_america_nord = set_de_date.loc[[11, 15, 20, 21, 28, 36, 47, 57, 78]]['Read'].mean()
medie_s_america_nord = set_de_date.loc[[11, 15, 20, 21, 28, 36, 47, 57, 78]]['Science'].mean()
print(medie_m_america_nord)

# calcule statistice pentru America de Sud
medie_m_america_sud = set_de_date.loc[[2, 7, 12, 14, 58, 59, 79]]['Math'].mean()
medie_r_america_sud = set_de_date.loc[[2, 7, 12, 14, 58, 59, 79]]['Read'].mean()
medie_s_america_sud = set_de_date.loc[[2, 7, 12, 14, 58, 59, 79]]['Science'].mean()
print(medie_m_america_sud)

# calcule statistice pentru Europa
medie_m_europa = set_de_date.loc[[1, 4, 6, 9, 16, 17, 18, 19, 22, 23, 24, 26, 27, 30, 31, 33, 35, 41, 42, 43, 46, 48, 50, 52, 54, 55, 61, 62, 64, 66, 68, 69, 70, 71, 72, 75, 77]]['Math'].mean()
medie_r_europa = set_de_date.loc[[1, 4, 6, 9, 16, 17, 18, 19, 22, 23, 24, 26, 27, 30, 31, 33, 35, 41, 42, 43, 46, 48, 50, 52, 54, 55, 61, 62, 64, 66, 68, 69, 70, 71, 72, 75, 77]]['Read'].mean()
medie_s_europa = set_de_date.loc[[1, 4, 6, 9, 16, 17, 18, 19, 22, 23, 24, 26, 27, 30, 31, 33, 35, 41, 42, 43, 46, 48, 50, 52, 54, 55, 61, 62, 64, 66, 68, 69, 70, 71, 72, 75, 77]]['Science'].mean()
print(medie_m_europa)

# calcule statistice pentru Australia [Australia & Noua Zeelanda]
medie_m_australia = set_de_date.loc[[3, 53]]['Math'].mean()
medie_r_australia = set_de_date.loc[[3, 53]]['Read'].mean()
medie_s_australia = set_de_date.loc[[3, 53]]['Science'].mean()
print(medie_m_australia)

# calcule statistice pentru țări care sunt în 2 continente [Azerbaijan, Georgia & Turcia]
medie_m_2 = set_de_date.loc[[5, 25, 74]]['Math'].mean()
medie_r_2 = set_de_date.loc[[5, 25, 74]]['Read'].mean()
medie_s_2 = set_de_date.loc[[5, 25, 74]]['Science'].mean()
print(medie_m_2)

459.6216216216216
440.04545454545456
389.1111111111111
384.2857142857143
365.0
483.0
413.3333333333333

In [57]:
import pandas as pd
rezultate = {
    'Name': ['Asia', 'Africa [Morocco]', 'America de Nord', 'America de Sud', 'Europa', 'Australia & Noua Zeelandă', '2 continente .az, .ge & .tr'],
    'Medie matematică': [medie_m_asia, medie_m_africa, medie_m_america_nord, medie_m_america_sud, medie_m_europa, medie_m_australia, medie_m_2],
    'Medie lectură': [medie_r_asia, medie_r_africa, medie_r_america_nord, medie_r_america_sud, medie_r_europa, medie_r_australia, medie_r_2],
    'Medie știință': [medie_s_asia, medie_s_africa, medie_s_america_nord, medie_s_america_sud, medie_s_europa, medie_s_australia, medie_s_2]
}
set_de_date_tabla.style.highlight_max(color = 'green')
set_de_date_tabla = pd.DataFrame(rezultate)
set_de_date_tabla

                          Name  Medie matematică  Medie lectură  Medie știință
0                         Asia        440.045455     421.636364     441.727273
1             Africa [Morocco]        365.000000     339.000000     365.000000
2              America de Nord        389.111111     414.777778     414.666667
3               America de Sud        384.285714     411.285714     410.714286
4                       Europa        459.621622     454.486486     466.351351
5    Australia & Noua Zeelandă        483.000000     499.500000     505.500000
6  2 continente .az, .ge & .tr        413.333333     398.333333     413.333333

# Explicații & comentarii ale rezultatelor statistice

# Grafice relevante pentru ipoteză de lucru

# Explicații & comentarii ale graficelor

# Concluzii generale